# Generated by Django 2.2.7 on 2019-11-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='department',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
